[phases.setup]
nixPkgs = ["jdk17"]

[phases.install]
cmds = ["echo 'Using JDK 17'"]

[phases.build]
cmds = ["./gradlew clean build -x test"]

[start]
cmd = "java -Xmx512m -Dserver.port=$PORT -jar build/libs/muti-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"