[build]
builder = "NIXPACKS"
buildCommand = "./gradlew clean build -x test"

[deploy]
startCommand = "java -Xmx512m -Dserver.port=$PORT -jar build/libs/muti-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NIXPACKS_JDK_VERSION = "17"